---
abstract: 'read xls / write xls 读写 xls'
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XLS-Simple
requires:
  Excel::Writer::XLSX: 0
  Spreadsheet::Read: 0
version: 0.02
